import type { ParsedSkill, Policy } from "../types.js";

export function generateGenericReadme(skill: ParsedSkill, policy: Policy): string {
  return `# ${skill.frontmatter.name}

${skill.frontmatter.description}

## Version
${skill.frontmatter.version ?? "0.1.0"}

## Authors
${skill.frontmatter.authors?.join(", ") ?? "Unknown"}

## Usage

This is a portable skill bundle compatible with skills-kit.

### Running with skills-kit

\`\`\`bash
# Install skills-kit
npm install -g @skills-kit/cli

# Run the skill
skills-kit run . --input input.json

# Or inline:
echo '{"key": "value"}' | skills-kit run .
\`\`\`

### Running manually

The skill's entrypoint is: \`${skill.frontmatter.entrypoints?.[0] ?? "scripts/run.cjs"}\`

\`\`\`bash
echo '{"key": "value"}' | node ${skill.frontmatter.entrypoints?.[0] ?? "scripts/run.cjs"}
\`\`\`

## Input Schema

\`\`\`json
${JSON.stringify(skill.frontmatter.inputs ?? {}, null, 2)}
\`\`\`

## Output Schema

\`\`\`json
${JSON.stringify(skill.frontmatter.outputs ?? {}, null, 2)}
\`\`\`

## Policy

- **Network**: ${policy.network ? "allowed" : "blocked"}
- **Filesystem Read**: ${policy.fs_read.length > 0 ? policy.fs_read.join(", ") : "none"}
- **Filesystem Write**: ${policy.fs_write.length > 0 ? policy.fs_write.join(", ") : "none"}
- **Exec Allowlist**: ${policy.exec_allowlist.length > 0 ? policy.exec_allowlist.join(", ") : "none"}
- **Domains Allowlist**: ${policy.domains_allowlist.length > 0 ? policy.domains_allowlist.join(", ") : "none"}

## Capabilities

${skill.frontmatter.capabilities?.join(", ") ?? "none specified"}

## Targets

${skill.frontmatter.targets?.join(", ") ?? "generic"}

---

Generated by [skills-kit](https://github.com/your-org/skills-kit)
`;
}
